# -*- coding: utf-8 -*-
"""assesment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1stJNv40YObalzsgE1yIa2B2LP0rmi0fZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dp = pd.read_csv('/content/historical_automobile_sales.csv')
dp.head()

# 1. Develop a Line chart using the functionality of pandas to show how automobile sales fluctuate from year to year.
dp.groupby(['Year'])['Automobile_Sales'].mean().plot(kind='line')

# 2.Plot different lines for categories of vehicle type and analyze the trend to answer the question Is there a noticeable difference in sales trends
#  between different vehicle types during recession periods?

sns.barplot(x='Vehicle_Type', y='Automobile_Sales',hue = 'Recession' ,  data=dp[dp['Recession'] == 1])

# 3.Use the functionality of Seaborn Library to create a visualization to compare the sales trend per vehicle type for a recession period with a non- recession period.
sns.lineplot(data=dp,
             x='Year',
             y='Automobile_Sales',
             hue='Vehicle_Type',
             style='Recession')

# 4.Now you want to compare the sales of different vehicle types during a recession and a non-recession period
sns.barplot(x='Vehicle_Type', y='Automobile_Sales',hue = 'Recession' ,  data=dp)