# -*- coding: utf-8 -*-
"""assesment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIbQFVQKSbUm_uy88CGc09HdaKmaK-HJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# 1.Import pandas and read in the banklist.csv file into a dataframe called banks.
banks = pd.DataFrame(pd.read_csv('/content/banklist.csv'))
banks

#2.Show the head of the dataframe.

banks.head()

# 3.What are the column names?
banks.columns

# 4.How many States (ST) are represented in this data set?
banks.value_counts('ST')

# 5.Get a list or array of all the states in the data set.
banks['ST'].unique()

# 6.What are the top 5 states with the most failed banks?
banks.value_counts('ST').head()

# 7.What are the top 5 acquiring institutions?
banks['Acquiring Institution'].value_counts().head()

# 8.How many banks has the State Bank of Texas acquired? How many of them were actually in Texas?
dpp = banks[banks['Acquiring Institution'] == 'State Bank of Texas']
dpp

dp2 = banks[(banks['Acquiring Institution'] == 'State Bank of Texas') & (banks['ST'] == 'TX')]
dp2

# 9.What is the most common city in California for a bank to fail in?
banks[banks['ST'] == 'CA']['City'].value_counts().head(1)